# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  gatsby-orb: orangegrove1955/gatsby-orb@1.0.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  gatsby_build-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - gatsby-orb/build
workflows:
  gatsby_build-workflow:
    jobs:
      - gatsby_build-job
